name: Build MY.AspNetCore.Mvc.ModelBinding

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 3.1.301

        - name: Install dependencies
          run: dotnet restore src/MY.*.sln

        - name: Build
          run: dotnet build src/MY.AspNetCore.Mvc.ModelBinding.sln --configuration Release --no-restore
